### ISSUE TITLE
Anormal RAM usage

### ISSUE THREAD

**Issue by Leirof** [Gunivers/Blazing-Scaffolding#10]
The server is using all the available RAM

Possibles causes:

- Problem with server configuration -> try to create several other servers
- Problem due to new version -> try to copy the map in a schem and paste it on an 1.18.2 generated map
- Problem due to the datapack -> use /perf command to locate the source

**Comment by VForiel** [comment]
Ce bug n'a pas été constaté depuis un bon moment, je le considère donc résolu
