### ISSUE TITLE
Lava layer duplication

### ISSUE THREAD

**Issue by Leirof** [Gunivers/Blazing-Scaffolding#9]
- When the server is stopped during a game, the entity that manage the lava layer is not removed. It result of two lava layers during the next game.
- Solution: kill all entity that manage the lava layer at the begining of the game

**Comment by LeiRoF** [comment]
From Loumardes:

> that's not the problem, the only command summoning this entity is :
> execute unless entity @e[type=marker,name="ScR_LavaLevel"] run summon minecraft:marker 1000 1 1000 {CustomName: '{"text":"ScR_LavaLevel"}'}
> so it shouldn't cause duplication

**Comment by LeiRoF** [comment]
There is one. The bug is pretty rare but it exist, we must find which conditions trigger it

**Comment by ascpial** [comment]
Does the bug ever append?

**Comment by LeiRoF** [comment]
Of course, otherwise we would not have created the issue ^^

**Comment by Theaustudio** [comment]
toujours d'actu ?
